server:
  port: 8081

spring:
  application:
    name: deck-service

  datasource:
    url: jdbc:postgresql://localhost:5433/deckdb
    driver-class-name: org.postgresql.Driver
    username: deck_user
    password: deck_pass

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

card-service:
  url: http://localhost:8080

resilience4j:
  circuitbreaker:
    instances:
      cardCatalog:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
  retry:
    instances:
      cardCatalog:
        maxAttempts: 2
        waitDuration: 200ms