services:

  # ===== Banco do deck-service =====
  deck-db:
    image: postgres:16-alpine
    container_name: deck-db
    environment:
      POSTGRES_DB: deckdb
      POSTGRES_USER: deck_user
      POSTGRES_PASSWORD: deck_pass
    ports:
      - "5433:5432"
    volumes:
      - deck-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U deck_user -d deckdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ===== Banco do card-creator-service =====
  creator-db:
    image: postgres:16-alpine
    container_name: creator-db
    environment:
      POSTGRES_DB: cardcreatordb
      POSTGRES_USER: creator_user
      POSTGRES_PASSWORD: creator_pass
    ports:
      - "5434:5432"
    volumes:
      - creator-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U creator_user -d cardcreatordb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ===== Zookeeper (necess√°rio para Kafka) =====
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # ===== Kafka =====
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 15s
      timeout: 10s
      retries: 5

volumes:
  deck-db-data:
  creator-db-data: